esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

logger:

api:
  reboot_timeout: 50min
  encryption:
    key: !secret api_key_tok

ota:
  password: !secret ota_api_password
  reboot_timeout: 50min

wifi:
  ssid: !secret wiwi_ssid
  password: !secret wiwi_pass
  fast_connect: on
  reboot_timeout: 50min
  ap:
    ssid: ${device_name_wifi}
    password: !secret wiwi_ap_pass

captive_portal:

sensor:
  - platform: wifi_signal
    name: Wifi signal esp
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: template
    name: Uptime esp
    id: uptime_esp
    icon: mdi:clock-start
    entity_category: diagnostic
    update_interval: 5min
    lambda: |-
      uint32_t dur=millis()/1000;
      char buffer[19];
      if(dur>=86400) sprintf(buffer,"%ud %uh %02um", dur/86400, dur%86400/3600, dur%3600/60);
      else if(dur>=3600) sprintf(buffer,"%uh %02um", dur/3600, dur%3600/60);
      else sprintf(buffer,"%um", dur/60);
      return {buffer};

button:
  - platform: restart
    name: Restart esp
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: Status esp
    entity_category: diagnostic
